from src.agents.strategy_research_outputs import extract_strategy_research_suggestions


def test_extract_strategy_research_suggestions_returns_standard_schema():
    result = extract_strategy_research_suggestions("# 策略研究")

    assert result == {
        "note": "Generated by StrategyResearchAgent. Human review required.",
        "strategy_hypotheses": [],
        "parameter_search_suggestions": [],
        "risk_control_suggestions": [],
        "requires_human_review": True,
    }
