from src.agents.parameter_iteration_outputs import extract_parameter_search_space_candidate


def test_extract_parameter_search_space_candidate_returns_standard_schema():
    result = extract_parameter_search_space_candidate("# report")

    assert result == {
        "note": "Generated by ParameterIterationAgent. Human review required before applying.",
        "requires_human_review": True,
        "do_not_auto_apply": True,
        "parameter_search_space_candidates": [],
        "risk_control_parameter_candidates": [],
        "research_questions": [],
    }
