"""Structured output helpers for ParameterIterationAgent reports."""

from __future__ import annotations


def extract_parameter_search_space_candidate(markdown_text: str) -> dict:
    """Return a stable placeholder schema for human-reviewed parameter candidates."""
    _ = markdown_text
    return {
        "note": "Generated by ParameterIterationAgent. Human review required before applying.",
        "requires_human_review": True,
        "do_not_auto_apply": True,
        "parameter_search_space_candidates": [],
        "risk_control_parameter_candidates": [],
        "research_questions": [],
    }
