"""Structured output helpers for StrategyResearchAgent reports."""

from __future__ import annotations


def extract_strategy_research_suggestions(markdown_text: str) -> dict:
    """Return a stable placeholder schema for human-reviewed research candidates."""
    _ = markdown_text
    return {
        "note": "Generated by StrategyResearchAgent. Human review required.",
        "strategy_hypotheses": [],
        "parameter_search_suggestions": [],
        "risk_control_suggestions": [],
        "requires_human_review": True,
    }
